<?php
return [
    [
        "title" => "League of Legends",
        "genre" => "MOBA",
        "type" => "Game",
        "cover_img" => "https://m.media-amazon.com/images/I/61CT6gENAgL._AC_SX679_.jpg",
        "stock" => 10,
        "editor" => "Riot Games",
        "plateform" => "PC",
        "pegi" => "12",
        "description" => "A competitive team-based game where players battle in strategic arenas.",
    ],
    [
        "title" => "The Great Gatsby",
        "genre" => "Drame",
        "type" => "Book",
        "cover_img" => "https://m.media-amazon.com/images/I/91yg5rniqwL._SL1500_.jpg",
        "stock" => 4,
        "author" => "F. Scott Fitzgerald",
        "isbn" => "9780743273565",
        "pages" => 180,
        "published_year" => 1925,
        "summary" => "A mysterious millionaire pursues the woman he loves in the Jazz Age."
    ],
    [
        "title" => "Halo Infinite",
        "genre" => "FPS",
        "type" => "Game",
        "cover_img" => "https://m.media-amazon.com/images/I/41Sd2niUqaS._AC_.jpg",
        "stock" => 7,
        "editor" => "343 Industries",
        "plateform" => "Xbox",
        "pegi" => "16",
        "description" => "The legendary Master Chief returns in the next chapter of the Halo franchise."
    ],
    [
        "title" => "Inception",
        "genre" => "Science Fiction",
        "type" => "Movie",
        "cover_img" => "https://m.media-amazon.com/images/I/91b3Xtjt0IL._AC_SY550_.jpg",
        "stock" => 5,
        "director" => "Christopher Nolan",
        "duration" => 148,
        "published_year" => 2010,
        "synopsis" => "A thief steals information by entering dreams.",
        "certification" => "Tous publics",
    ],
    [
        "title" => "To Kill a Mockingbird",
        "genre" => "Drame",
        "type" => "Book",
        "cover_img" => "https://m.media-amazon.com/images/I/81c6aew79KL._SL1500_.jpg",
        "stock" => 2,
        "author" => "Harper Lee",
        "isbn" => "9780061120084",
        "pages" => 281,
        "published_year" => 1960,
        "summary" => "A young girl grows up in a racially divided Southern town and learns about justice."
    ],
    [
        "title" => "Super Mario Odyssey",
        "genre" => "Fantaisie",
        "type" => "Game",
        "cover_img" => "https://m.media-amazon.com/images/I/71XZsDkAuNL._AC_SL1500_.jpg",
        "stock" => 5,
        "editor" => "Nintendo",
        "plateform" => "Nintendo",
        "pegi" => "7",
        "description" => "Mario embarks on a globe-trotting adventure with his hat companion Cappy.",
    ],
    [
        "title" => "Interstellar",
        "genre" => "Science Fiction",
        "type" => "Movie",
        "cover_img" => "https://m.media-amazon.com/images/I/71y3gZHem8L._AC_SL1500_.jpg",
        "stock" => 6,
        "director" => "Christopher Nolan",
        "duration" => 169,
        "published_year" => 2014,
        "synopsis" => "A team of explorers travel through a wormhole in search of a new home for humanity.",
        "certification" => "Tous publics",
    ],
    [
        "title" => "The Witcher 3",
        "genre" => "RPG",
        "type" => "Game",
        "cover_img" => "https://m.media-amazon.com/images/I/71CL57pekML._AC_SX425_.jpg",
        "stock" => 3,
        "editor" => "CD Projekt Red",
        "plateform" => "PC",
        "pegi" => "18",
        "description" => "A monster hunter embarks on a journey to find his adopted daughter.",
    ],
    [
        "title" => "Pulp Fiction",
        "genre" => "Thriller-Suspense",
        "type" => "Movie",
        "cover_img" => "https://m.media-amazon.com/images/I/71zSZQzlK+L._AC_SY879_.jpg",
        "stock" => 4,
        "director" => "Quentin Tarantino",
        "duration" => 154,
        "published_year" => 1994,
        "synopsis" => "Interwoven stories of crime and redemption in Los Angeles.",
        "certification" => "-16",
    ],
    [
        "title" => "1984",
        "genre" => "Science Fiction",
        "type" => "Book",
        "cover_img" => "https://m.media-amazon.com/images/I/71dess3q1bL._SY425_.jpg",
        "stock" => 1,
        "author" => "George Orwell",
        "isbn" => "9780451524935",
        "pages" => 328,
        "published_year" => 1949,
        "summary" => "A dystopian future where Big Brother controls every aspect of life."
    ],
    [
        "title" => "The Godfather",
        "genre" => "Drame",
        "type" => "Movie",
        "cover_img" => "https://m.media-amazon.com/images/I/510L5ypQBdL._AC_SY879_.jpg",
        "stock" => 2,
        "director" => "Francis Ford Coppola",
        "duration" => 175,
        "published_year" => 1972,
        "synopsis" => "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",
        "certification" => "-16",
    ],
    [
        "title" => "The Hobbit",
        "genre" => "Fantaisie",
        "type" => "Book",
        "cover_img" => "https://m.media-amazon.com/images/I/81hylMcxa3L._SL1500_.jpg",
        "stock" => 3,
        "author" => "J.R.R. Tolkien",
        "isbn" => "9780547928227",
        "pages" => 310,
        "published_year" => 1937,
        "summary" => "Bilbo Baggins embarks on an unexpected journey with dwarves to reclaim a lost kingdom."
    ],
    [
        "title" => "Dark Souls III",
        "genre" => "RPG",
        "type" => "Game",
        "cover_img" => "https://m.media-amazon.com/images/M/MV5BMjg5MGI3ZWUtODc4NS00Y2E2LWE1MTQtZDAwM2Q4ZDJlNzg5XkEyXkFqcGc@._V1_FMjpg_UX1200_.jpg",
        "stock" => 4,
        "editor" => "FromSoftware",
        "plateform" => "PlayStation",
        "pegi" => "16",
        "description" => "An action RPG where players battle their way through a dark fantasy world.",
    ],
    [
        "title" => "The Shining",
        "genre" => "Horreur",
        "type" => "Movie",
        "cover_img" => "https://m.media-amazon.com/images/M/MV5BNmM5ZThhY2ItOGRjOS00NzZiLWEwYTItNDgyMjFkOTgxMmRiXkEyXkFqcGc@._V1_FMjpg_UX627_.jpg",
        "stock" => 3,
        "director" => "Stanley Kubrick",
        "duration" => 146,
        "published_year" => 1980,
        "synopsis" => "A family heads to an isolated hotel where a sinister presence influences the father.",
        "certification" => "-16",
    ],
    [
        "title" => "Avatar",
        "genre" => "Science Fiction",
        "type" => "Movie",
        "cover_img" => "https://m.media-amazon.com/images/I/91N1lG+LBIS._AC_SL1500_.jpg",
        "stock" => 8,
        "director" => "James Cameron",
        "duration" => 162,
        "published_year" => 2009,
        "synopsis" => "A marine on an alien planet becomes torn between following orders and protecting his new home.",
        "certification" => "Tous publics",
    ],
    [
        "title" => "Cyberpunk 2077",
        "genre" => "RPG",
        "type" => "Game",
        "cover_img" => "https://m.media-amazon.com/images/I/71dC3-76snL._AC_SY879_.jpg",
        "stock" => 6,
        "editor" => "CD Projekt Red",
        "plateform" => "PC",
        "pegi" => "18",
        "description" => "An open-world RPG set in a futuristic dystopian city.",
    ],
    [
        "title" => "Brave New World",
        "genre" => "Science Fiction",
        "type" => "Book",
        "cover_img" => "https://m.media-amazon.com/images/I/91D4YvdC0dL._SL1500_.jpg",
        "stock" => 2,
        "author" => "Aldous Huxley",
        "isbn" => "9780060850524",
        "pages" => 311,
        "published_year" => 1932,
        "summary" => "A futuristic society engineered for stability hides deep flaws beneath its utopian surface."
    ],
    [
        "title" => "Gladiator",
        "genre" => "Action",
        "type" => "Movie",
        "cover_img" => "https://m.media-amazon.com/images/I/71wjnt1uIpL._AC_SL1500_.jpg",
        "stock" => 5,
        "director" => "Ridley Scott",
        "duration" => 155,
        "published_year" => 2000,
        "synopsis" => "A betrayed Roman general seeks revenge against the corrupt emperor who murdered his family.",
        "certification" => "-16",
    ],
    [
        "title" => "The Last of Us",
        "genre" => "RPG",
        "type" => "Game",
        "cover_img" => "https://m.media-amazon.com/images/I/81mu67Py8WL._AC_SL1500_.jpg",
        "stock" => 4,
        "editor" => "Naughty Dog",
        "plateform" => "PlayStation",
        "pegi" => "18",
        "description" => "A smuggler and a teenage girl journey across a post-apocalyptic United States.",
    ],
    [
        "title" => "Shutter Island",
        "genre" => "Mystère",
        "type" => "Movie",
        "cover_img" => "https://m.media-amazon.com/images/I/71ZUy8y-3CL._AC_SL1500_.jpg",
        "stock" => 3,
        "director" => "Martin Scorsese",
        "duration" => 138,
        "published_year" => 2010,
        "synopsis" => "Two U.S. marshals investigate the disappearance of a prisoner from an asylum.",
        "certification" => "-16",
    ],
    [
        "title" => "The Road",
        "genre" => "Drame",
        "type" => "Book",
        "cover_img" => "https://m.media-amazon.com/images/I/51URLMJvQ7L._SL1000_.jpg",
        "stock" => 2,
        "author" => "Cormac McCarthy",
        "isbn" => "9780307387899",
        "pages" => 287,
        "published_year" => 2006,
        "summary" => "A father and son struggle to survive while traveling through a post-apocalyptic landscape."
    ],
    [
        "title" => "Fight Club",
        "genre" => "Documentaire",
        "type" => "Movie",
        "cover_img" => "https://m.media-amazon.com/images/I/61IgtYrLF5L._AC_SL1280_.jpg",
        "stock" => 4,
        "director" => "David Fincher",
        "duration" => 139,
        "published_year" => 1999,
        "synopsis" => "An insomniac office worker forms a secret fight club with a soap maker.",
        "certification" => "-16",
    ],
    [
        "title" => "Animal Farm",
        "genre" => "Fantaisie",
        "type" => "Book",
        "cover_img" => "https://m.media-amazon.com/images/I/619GyNyTTKL._SL1500_.jpg",
        "stock" => 3,
        "author" => "George Orwell",
        "isbn" => "9780451526342",
        "pages" => 112,
        "published_year" => 1945,
        "summary" => "A group of farm animals overthrow their human farmer in pursuit of equality."
    ],
    [
        "title" => "Mass Effect 2",
        "genre" => "RPG",
        "type" => "Game",
        "cover_img" => "https://m.media-amazon.com/images/I/71XQcMKeK7L._AC_SY500_.jpg",
        "stock" => 5,
        "editor" => "BioWare",
        "plateform" => "Xbox",
        "pegi" => "18",
        "description" => "Commander Shepard recruits a team to stop a new alien threat to humanity.",
    ],
    [
        "title" => "Saving Private Ryan",
        "genre" => "Comédie",
        "type" => "Movie",
        "cover_img" => "https://m.media-amazon.com/images/I/71aluwmPo-L._AC_SL1191_.jpg",
        "stock" => 2,
        "director" => "Steven Spielberg",
        "duration" => 169,
        "published_year" => 1998,
        "synopsis" => "A group of soldiers risk their lives to rescue a paratrooper during WWII.",
        "certification" => "-16",
    ],
    [
        "title" => "Silent Hill 2",
        "genre" => "FPS",
        "type" => "Game",
        "cover_img" => "https://m.media-amazon.com/images/I/71XsCEArGiL._AC_SL1500_.jpg",
        "stock" => 3,
        "editor" => "Konami",
        "plateform" => "PlayStation",
        "pegi" => "18",
        "description" => "A man searches for his deceased wife in a foggy, monster-infested town.",
    ],
    [
        "title" => "The Catcher in the Rye",
        "genre" => "Comédie Musicale",
        "type" => "Book",
        "cover_img" => "https://m.media-amazon.com/images/I/71Xu4akGK+L._SL1500_.jpg",
        "stock" => 2,
        "author" => "J.D. Salinger",
        "isbn" => "9780316769488",
        "pages" => 277,
        "published_year" => 1951,
        "summary" => "Holden Caulfield recounts his experiences in New York after being expelled from school."
    ],
    [
        "title" => "Mad Max: Fury Road",
        "genre" => "Action",
        "type" => "Movie",
        "cover_img" => "https://m.media-amazon.com/images/I/71cejF7FuML._AC_SL1500_.jpg",
        "stock" => 7,
        "director" => "George Miller",
        "duration" => 120,
        "published_year" => 2015,
        "synopsis" => "In a post-apocalyptic wasteland, a drifter teams with a rebel to escape a tyrant.",
        "certification" => "-16",
    ],
];
